### ISSUE TITLE
请问，将一个L2_loss改成IOUloss，哪些地方需要注意和修改？

### ISSUE THREAD

**Issue by chenweiqian** [wcj-Ford/IOULoss#1]
我将ground truth的表示改成unibox那种形式的，prediction也改成unitbox表示的，但是loss还是Nan。希望您能回复我，谢谢！

**Comment by wcj-Ford** [comment]
代码还在调试， 你要改直接做个减法然后平方就可以了！

**Comment by chenweiqian** [comment]
我改的是SSD的代码，觉得预测位置那边有点搞不清楚。我将ground turh改成unitbox里的t，b，l，r形式，将预测框，通过x=Aw*dx(A)+Ax; y=Ah*dy(A)+Ay; w=Aw*exp(dw(A)); h=Ah*exp(dh(A))，再进一步改成t，b，l，r的形式，但是这样loss也是nan。我觉得其中我有地方没理解清楚，但是没有什么头绪，希望您能指点一下。

**Comment by wcj-Ford** [comment]
loss输入的数据必须为正， 在loss层前面加ReLU，试下。

**Comment by chenweiqian** [comment]
已经加了。我就是有个地方不明白：像faster-rcnn或者SSD这样的在计算loss的时候，网络导致的预测框值一定是相对于默认框而言的y，x，w，h吗？还是是人为写的？如果人为写的，我找不到表示这部分意思的代码。

**Comment by wcj-Ford** [comment]
建议你看下这个http://caffecn.cn/?/question/160

**Comment by chenweiqian** [comment]
谢谢！

**Comment by chenweiqian** [comment]
请问relu函数和relu层一样吗？

**Comment by wcj-Ford** [comment]
mxnet.symbol.Activation(data=data, act_type='relu')

**Comment by chenweiqian** [comment]
谢谢！

**Comment by chenweiqian** [comment]
打扰你了，loss不会nan后，新问题就出现了。如果我用的是pre-trained模型的话，改了loss，是不是要全部从头训练？我试过从头和微调，loss感觉都不是很大，但是检测不到物体，这大概是什么情况？

**Comment by wcj-Ford** [comment]
这个很难训练，我问过作者，作者建议是先train好一个人脸检测的model然后换用IOULoss微调。

**Comment by chenweiqian** [comment]
两种不一样的loss是可以微调的吗？

**Comment by chenweiqian** [comment]
非常感谢你的回答！

**Comment by chenweiqian** [comment]
不好意思，再次打扰您了。我发现将原本计算x，y，h，w的loss，改成计算t，b，l，r的。loss变小了好多，但是map不高。请问这有可能是什么情况？

**Comment by wcj-Ford** [comment]
抱歉才疏学潜，回答不了您的问题。

**Comment by wcj-Ford** [comment]
x,y,w,h是每一张图对应的人脸的标签都一样，t,b,l,r只有对应人脸的行或者列标签是一样。

**Comment by chenweiqian** [comment]
恩恩，谢谢你的回复!
